# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:11
#         env:
#           POSTGRES_USER: rails_github_actions
#           POSTGRES_DB: rails_github_actions_test
#           POSTGRES_PASSWORD: postgres
#         ports: ["5432:5432"]
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#     steps:
#       - uses: actions/checkout@v1
#       - name: Set up Ruby
#         uses: actions/setup-ruby@v1
#         with:
#           ruby-version: 2.7.x
#       - name: Set up Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14.15.5
#       - name: Install dependencies
#         run: |
#           sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
#           gem install bundler
#           bundle install --jobs 4 --retry 3
#           yarn install
#       - name: Setup test database
#         env:
#           RAILS_ENV: test
#           PGHOST: localhost
#           POSTGRES_DB: rails_github_actions_test
#           POSTGRES_USER: rails_github_actions
#           POSTGRES_PASSWORD: postgres
#         run: |
#           cp config/database.ci.yml config/database.yml
#           rake db:create db:migrate
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
#           heroku_email: "patrick.lionnel@finetechgroup.com"